name: Update Nextcloud Docker Images

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  update-nextcloud-latest:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Check if Nextcloud Latest Image Updated
      id: nextcloud_latest_update_check
      uses: lucacome/docker-image-update-checker@v1
      with:
        base-image: "nextcloud:latest"
        image: "${{ secrets.DOCKERHUB_USERNAME }}/nextcloud:latest"

    - name: Login to DockerHub
      if: steps.nextcloud_latest_update_check.outputs.needs-updating == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Update Nextcloud Latest Image
      if: steps.nextcloud_latest_update_check.outputs.needs-updating == 'true'
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: ./scripts/update-nextcloud.sh latest

  update-nextcloud-fpm:
    runs-on: ubuntu-latest
    needs: update-nextcloud-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Check if Nextcloud FPM Image Updated
      id: nextcloud_fpm_update_check
      uses: lucacome/docker-image-update-checker@v1
      with:
        base-image: "nextcloud:fpm"
        image: "${{ secrets.DOCKERHUB_USERNAME }}/nextcloud:fpm"

    - name: Login to DockerHub
      if: steps.nextcloud_fpm_update_check.outputs.needs-updating == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Update Nextcloud FPM Image
      if: steps.nextcloud_fpm_update_check.outputs.needs-updating == 'true'
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: ./scripts/update-nextcloud.sh fpm
